#include "exception.h"

GENERATE_EXCEPTION_IMPL(ShaderException)
GENERATE_EXCEPTION_IMPL(WindowException)
GENERATE_EXCEPTION_IMPL(DisplayException)
GENERATE_EXCEPTION_IMPL(LoggingException)
GENERATE_EXCEPTION_IMPL(ImageException)
